### ISSUE TITLE
API integration

### ISSUE THREAD

**Issue by eriysd** [natapokie/ai-fashion-mirror#40]
# Description

## Part 1
_if prof says yes to rewriting:_ 
- integrate the open API call 
- send the new prompt and receive JSON file

_else:_
- modify the existing open API call to send the new prompt and receive the desired JSON file 

### Additional task breakdowns and suggestions

Instead of calling the PRE API, we want to call openAI directly to generate clothing feedback based on the captured image
1. install [openai npm package](https://www.npmjs.com/package/openai/v/4.0.0-beta.4) 
    - this allows us to easily make requests to OpenAI server
2. create new prompts (using the prof's prompt as a reference) https://platform.openai.com/docs/overview
3. testing prompts with your own API key
    - you can login to OpenAI with your google account (or whatever you usually use for chatgpt)
    - you can create your own secret keys here, https://platform.openai.com/settings/organization/api-keys (although not sure about the limit :(
    - more references on making requests https://platform.openai.com/docs/api-reference/making-requests
    - quickstart guide also has examples, https://platform.openai.com/docs/quickstart
    - recommend trying a few test prompts via python since it's easier to set up? (if you are testing, please include it in the repo though so we have records of everything!)
5. integrate the prompt chain/agent with the node js server

We also want to make use of the **person detection** call from the PRE API -- and rewrite that or incorporate that into our code.

And finally (future pr), we want to incorporate the **voice generation** which is also done through open ai,
https://platform.openai.com/docs/guides/text-to-speech/overview

## Part 1.2

- [ ] add routes & controllers
  - create a route, and use postman to test if it is connected -- before starting   
  - in controller, make sure to add error handlers similar to camera (think about different images inputs, and what might throw errors)
- [ ] modify service to take in form-data input
- [ ] test to backend request works
- [ ] integrate with frontend
  - create a new function in the services directory that makes a request to the server
  - modify the page, so that the server is called in the right place

## Part 2
- integrate the weather API
- update the open API prompt to incorporate the weather info
